version: '3'

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
       MONGO_INITDB_ROOT_USERNAME: root
       MONGO_INITDB_ROOT_PASSWORD: root
       MONGO_INITDB_DATABASE: transaction-api
    volumes:
      - ./mongoSetup.js:/docker-entrypoint-initdb.d/mongoSetup.js:ro